---
name: Deploy rasa
run-name: Deploying Rasa
on:
  push:
    branches: [dev]
jobs:
  Deploy-latest-changes:
    runs-on: ubuntu-latest
    environment: deploy_dev
    steps:
      - uses: actions/checkout@v3
      - name: Run playbook
        env:
          DROPLET_IP: ${{ vars.DROPLET_IP }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_URL: ${{ vars.DB_URL }}
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: deploy/main.yml
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, additional flags to pass to ansible-playbook
          options: |-
            --inventory deploy/hosts.yml
            --extra-vars @deploy/defaults/main.yml 
            --verbose
