---
name: Convert yaml NLU data to csv
run-name: Converting NLU data
on:
  push:
    branches: [main]
jobs:
  Convert-NLU-data:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: checkout repo content
        uses: actions/checkout@v3
        with:
          python-version: '3.10' # install the python version needed
      - name: setup python
        run: actions/setup-python@v4
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pathlib pyaml pandas clumper parse

      - name: execute py script # run main.py
        run: python scripts/utility.py
